core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

ecommercesite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # media files

userauths/urls.py
from django.urls import path

from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('sign-up/', views.register_user, name='sign-up'),
    path('sign-in/', views.login_user, name='sign-in'),
    path('sign-out/', views.logout_user, name='sign-out'),
]

userauths/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    def __str__(self):
        return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserRegister(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))

    class Meta:
        model = User
        fields = ['username', 'email', ]

userauths/views.py
from django.shortcuts import render, redirect
from .forms import UserRegister

from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from .models import User

# User = settings.AUTH_USER_MODEL

def register_user(request):
    """Register View for the creation of user accounts"""

    if request.method == 'POST':
        form = UserRegister(request.POST)

        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')

            messages.success(request, f'Hey {username}, your account was created successfully')
            new_user = authenticate(username=form.cleaned_data.get('email'),
                                    password=form.cleaned_data.get('password1')
            )

            login(request, new_user)
            return redirect('core:index')

    else:
        form = UserRegister()
    
    context = {
        'form': form,
    }

    return render(request, 'userauths/sign-up.html', context)


def login_user(request):
    """Login View for authenticating/logging in user accounts"""

    if request.user.is_authenticated:
        messages.warning(request, 'You are already logged in')
        return redirect('core:index')
        
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user:
                login(request, user)
                messages.success(request, 'You are now logged in')

                return redirect('core:index')
            else:
                messages.warning(request, 'User does not exist, Create an account')

        except:
            messages.warning(request, f"User with {email} does not exist")


    return render(request, 'userauths/sign-in.html')


def logout_user(request):
    """Logout View for the logout function"""
    
    logout(request)
    messages.success(request, 'You Logged out')
    return redirect('userauths:sign-in')

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-light text-dark" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">
                <form method="POST">
                    {% csrf_token %}
                    
                    <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                    <p class="text-dark-50 mb-5">Please enter your login and password!</p>

                    <div class="form-outline form-white mb-4">
                        <label class="form-label fw-bold" for="typeEmailX">Email</label>
                        <input type="email" id="typeEmailX" class="form-control form-control-lg" required name="email" />
                        
                    </div>

                    <div class="form-outline form-white mb-4">
                        <label class="form-label fw-bold" for="typePasswordX">Password</label>
                        <input required type="password" id="typePasswordX" class="form-control form-control-lg" name="password" />
                        
                    </div>

                    <button class="btn btn-outline-dark btn-lg px-5" type="submit">Login</button>
                    </div>

                    <div>
                    <p class="mb-0">Don't have an account? <a href="{% url 'userauths:sign-up' %}" class="text-black-50 fw-light">Sign Up</a>
                    </p>

                </form>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}


{% block content %}

<body>
  <div class="outerlayer">
    <div class="wrapper">

      {% if form.errors %}
      <div class="alert alert-danger">
        <strong>{{ form.errors }}}</strong>
      </div>
      {% endif %}

      <h2>Registration</h2>
      <form action="#" method="POST">
        {% csrf_token %}
        <div class="input-box">
          {{ form.username }}
        </div>
        <div class="input-box">
          {{ form.email }}
        </div>
        <div class="input-box">
          {{ form.password1 }}
        </div>
        <div class="input-box">
          {{ form.password2 }}
        </div>
        <div class="policy">
          <input type="checkbox">
          <h3>I accept all terms & condition</h3>
        </div>
        <div class="input-box button">
          <input type="Submit" value="Register Now">
        </div>
        <div class="text">
          <h3>Already have an account? <a href="{% url 'userauths:sign-in' %}">Login now</a></h3>
        </div>
      </form>
    </div>
  </div>
</body>

{% endblock %}